### ISSUE TITLE
Task - New (Edit) taxon name - implement modal for syncronize attributes

### ISSUE THREAD

**Issue by mjy** [SpeciesFileGroup/taxonworks#1449]
When I update a parent, and I am creating a new subsequent combination, then I want to be prompted, on save, to also trigger OTU syncronization in #1448.

* [ ] Only trigger when previously saved (has ID) and `parent_id` will change
* [ ] On Save event pull up modal, 'Parent has changed!`
* [ ] add params to UPDATE as defined in pic

![Screen Shot 2020-04-22 at 1 59 59 PM](https://user-images.githubusercontent.com/22600/80022384-9c978c00-84a1-11ea-861a-d39621543390.png)

**Comment by mjy** [comment]
@proceps Please comment if you wish- we're going to do this pretty quick.

**Comment by proceps** [comment]
This is not right. Protonym is always associated with the original combination. If you change the parent, the original combination stay the same. And when cited, the original combination is cited (that what you see in browse nomenclature when you cite a protonym). If you want to cite a new combination, you have to add OTU to this combination, not to move otu from the protonym. This will be extremely confusing, when suddenly you cannot find the data associated with this name (distribution, host plants, determinations, etc.) In the proposed scenario, all of this will move to another name.

**Comment by mjy** [comment]
I think you are missundestanding- let's talk then work this out (tomorrow perhaps).  This has nothing to do with the original combination, it has to do with OTUs attached to Protonym vs. Combination.

Scenario:

* Aus bus Smith, 1920
* Bus bus (Smith, 1920) 
  * Asserted distribution added to the OTU linked to Bus at this point
* Cus dus (Smith, 1920)
  * !! OTU on AssertedDistribution now reads "Cus dus (Smith, 1920)", it shouldn't it should read "Bus bus (Smith, 1920)"
  * !! Citations on Bus bus (Smith, 1920) now read as citations on Cus bus (Smith, 1920), not the prior combination

What todo?

**Comment by mjy** [comment]
Ahh - I see potential confusion- I was referencing original comination, updating picture!

**Comment by mjy** [comment]
Fixed picture

**Comment by proceps** [comment]
I proposed long time ago, that OTU label is linked always to original combination name. Than when you make determination, and if you want to use current name, you will be forced to link the determination to OTU associated with a combination. If TaxonName change, you still have the determination linked to proper string.

Partially it is also linked to another issue which we have open. Create OTU when needed. When you search for a Species string, this TaxonName (Protonym or Combination) exists in the database, but it does not have associated OTU, the OTU is created on demand, when you search for it, and create the determination.
May be we need some additional method which will change OTU label when needed. Show the original determination. Show current TaxonName.

**Comment by mjy** [comment]
Yes. I think we're on the same page with data representation, it's just a matter of implementation.

**Comment by mjy** [comment]
> May be we need some additional method which will change OTU label when needed. Show the original determination. Show current TaxonName.

When you say "change OTU label" you really mean change OTU, right?  Like reference a name, then resolve it to the correct OTU?

**Comment by proceps** [comment]
should we close this?

**Comment by mjy** [comment]
No.
